# Model arguments
model_name_or_path: /home/l069561/project/models/Meta-Llama-3-8B #togethercomputer/StripedHyena-Hessian-7B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
chat_template: "{% if messages[0]['role'] == 'system' %}{% set system_message = '### System Instruction: ' + messages[0]['content'] | trim + '' %}{% set messages = messages[1:] %}{% else %}{% set system_message = '' %}{% endif %}{{ bos_token + system_message }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '### Context: ' + message['content'] | trim + '' }}{% elif message['role'] == 'assistant' %}{{ '### Result: ' + message['content'] | trim + eos_token + '' }}{% endif %}{% endfor %}{% if add_generation_prompt %}{{ '### Result: ' }}{% endif %}"
dataset_mixer:
  /home/l069561/project/data/test_8k_nlp: 1.0
  # HuggingFaceH4/ultrachat_200k: 1.0
  # /home/l069561/project/data/processed_data_open_sourced_xml_to_text/merged_open_sourced_xml_to_text_dataset: 1.0
  # /home/l069561/project/data/sang_data_formatted: 1.0
dataset_splits:
- train_sft
- test_sft
preprocessing_num_workers: 4

# SFT trainer config
trust_remote_code: true
bf16: true
do_eval: false
# evaluation_strategy: epoch
eval_strategy: epoch
max_grad_norm: 1.0
# gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
log_level: info
logging_steps: 5
logging_strategy: steps
learning_rate: 2.0e-05
optim: adamw_torch # adamw_torch paged_adamw_32bit galore_adamw lion_32bit
optim_target_modules: all-linear
weight_decay: 0.01
lr_scheduler_type: cosine
max_seq_length: 8192
packing: false
dataset_num_proc: 16
max_steps: -1
num_train_epochs: 100
output_dir: /home/l069561/project/alignment-handbook/experiments/models/test_deepspeed
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1 # this is per device, you need to manual calculate global batch by per device * gas * gpu * node
gradient_accumulation_steps: 4
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
# - tensorboard
save_strategy: "no"
save_steps: 2500
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
